services:
  app:

    container_name: user-service
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8082:8082"
    networks:
      - msa-net


networks:
  msa-net:
    external: true
